language: node_js
node_js:
- '7.4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  postgresql: "9.5"
sudo: required
env:
- TRAVIS=travis CXX=g++-4.8
script:
- npm run travis-test
- npm run lint
after_script:
- npm run codecov
notifications:
  email: false
  slack:
    secure: XPl0bhie+kn46CKap25gKrcue9YwQbCgB4QNXHbxyJZocsgzuVI4fFVzbEsLXC0v/zHmt+0XPRV+PiPXyDRlmER2l+nIutZ6QEoKmFiJ+bOsjQyovsZaqTiUc4ZYhARY1QgFb1uKOH6EgKGZmJITUqyrLPWPwx1nSewFUip0azYe6P5Ac/2cLGQUWp88jCgiUelNnMW/JAqoF9JtOjH6ZLBdvABAGtclGjFvOVTYj5rWIOtC8Dh6W4KBaW7CqootaRLEqcOrlxFYH7BArqzKo2vC0jljICW46PxhhXZRWKcXWS4rZOdqEP6upDXytlBhVvBEe8FjRdXYgLMDxtC+ZLvJ/3BaUSnJVYNu6G7ZopSxYXQdp2dbCPV7U3aPQb4KNvQH9CZYhFeEDKCrioI9dz187sc1XaZ/UxXYjQiWDXqhJ8TXB3iCy4tQ1nuPQ716fQIzyzhKVgbECQbbhgAV0YztYDYaTCeKS3SvkiumI7F+b48WBwVNvYMIfVJO6ZVTfcfSJ6dtLVQeBWwp64SZcJy3Ol8zHKm4GUZcP6tvB0HER5onUwutlzA3SMdZmHaakldxNP32b0VfiVo+tm2LS8k0J9NNeajSWqfGZJLZFnq98+P6R4C5coxrEaREir1nIW0N2H4kHaPfwpS5TN4kx7+cYPpqO0nMEGhgmg4P2GE=
