codecov:
  branch: master

coverage:

  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default:
        target: auto
        threshold: 1

    patch:
      default:
        target: auto

    changes:
      default:

  ignore:
    - test/.*
    - node_modules/.*
    - coverage/.*
    - docs/.*
    - resources/.*
    - config/.*

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
