codecov:
  branch: master

coverage:
  
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 1
        branches: *

    patch:
      default:
        target: auto
        branches: *

    changes:
      default:
        branches: *

  ignore:
    - test/.*
    - node_modules/.*
    - coverage/.*
    - docs/.*
    - resources/.*
    - config/.*

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
